CREATE DATABASE IF NOT EXISTS yield_sync1;

USE yield_sync1;

CREATE TABLE `user` (
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	admin TINYINT(1) DEFAULT 0,
	verified TINYINT(1) DEFAULT 0,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE(email)
);