name: Build and Deploy to Railway

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Server
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clone Frontend Submodule
        run: git clone https://github.com/yield-sync/frontend.git frontend

      - name: Install & Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Copy Frontend Build to Server
        run: |
          mkdir -p ./static
          echo "Copying frontend to static folder"
          cp -r frontend/dist/* ./static
          ls -la ./static

      - name: Deploy to Railway
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          railway up --service server
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
